version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_AUTH_MODE=basic
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://clover:supersecret@db:5432/cloverdb
      - JWT_SECRET=your_jwt_secret_key
      - AUTH_MODE=basic
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=cloverdb
      - POSTGRES_USER=clover
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: